### ISSUE TITLE
Typo in Sailthru_Client.php:1604

### ISSUE THREAD

**Issue by jessiehernandez** [sailthru/sailthru-php5-client#58]
There is a typo in the following lines:

`if (headers === null) {`

The above should be:

`if ($headers === null) {`

**Comment by aingram** [comment]
@mydagobah

**Comment by MackenzieM** [comment]
We at [RealSelf](https://github.com/RealSelf) have run into blocking errors in v1.2.0 because of this.

**Comment by eweiser** [comment]
Thanks for raising this issue, @jessiehernandez and @MackenzieM. v1.2.1 has the necessary fixes and should be available on packagist shortly.

**Comment by MackenzieM** [comment]
The issue is resolved for us, thanks for the follow-through.
