### ISSUE TITLE
PHP 7 plans?

### ISSUE THREAD

**Issue by rossmotley** [sailthru/sailthru-php5-client#64]
Hi,

Are there any plans for a PHP 7 compatible client? Would it be a new library given the naming of this one?

Thanks,

Ross

**Comment by wweihs** [comment]
rossmotley, just curious if you found any specific things within the client that weren't compatible with PHP7 other than the client name. 

-Wendy

**Comment by rossmotley** [comment]
@wweihs I didn't find any specific things, the project we'll be using with product with is currently on PHP 5.5 but we are planning on upgrading to 7 later this year.

I did create #65 with Travis, I think it would be helpful to see what PHP versions this lib is targeting.

**Comment by wweihs** [comment]
Thanks for the info. In the same boat.

**Comment by silverman63** [comment]
Hi, there is no current plan outlined, but I'd like to get that into the pipeline. The Travis PR is a great place to start- thank you for submitting! I'll be able to start looking into Travis as well as PHP7 plans later this month.  

In the mean time, if you encounter anything please post it here!

**Comment by rossmotley** [comment]
@silverman63 Thanks for the update

**Comment by silverman63** [comment]
@wweihs I tested against PHP7 in Travis successfully (see #65). Not sure what we'll be doing about repo-naming, but builds will continue to be tested against PHP7 in Travis once 65 is merged.
