### ISSUE TITLE
Release 1.2.4

### ISSUE THREAD

**Issue by djmarland** [sailthru/sailthru-php5-client#82]
The bug that was fixed in https://github.com/sailthru/sailthru-php5-client/pull/72 is also affecting us. We can see that it has been merged successfully.
Please can a new release be tagged so we can continue work without having to fork or target `dev-master`.

Thank you

**Comment by silverman63** [comment]
Hi @djmarland, I'll be releasing some point over the upcoming two weeks, breaking out a 2.x branch with the API-error-handling, and reverting the API-error-handling in 1.x (but keeping rest of new features).

**Comment by djmarland** [comment]
Thanks, I'll look forward to that

**Comment by djmarland** [comment]
2 weeks came and went and we still have to rely on a fork in our own code. Is this project abandoned?

**Comment by silverman63** [comment]
Hi @djmarland you're absolutely right. Not abandoned and I apologize that this never happened. 

I've released 1.2.4 and deleted the previous comment as that strategy was put on hold.

**Comment by djmarland** [comment]
Fantastic. Thank you
