### ISSUE TITLE
Invalid email Sailthru_Client_Exception error code doesn't match

### ISSUE THREAD

**Issue by dustinpaluch** [sailthru/sailthru-php5-client#84]
I'm getting a code 99 for the "Invalid email: {EMAIL}" error, but the documentation and error code const (https://github.com/sailthru/sailthru-php5-client/blob/master/sailthru/Sailthru_Client_Exception.php#L11) say it should be 11. 

![Screen Shot 2020-01-30 at 4 17 09 PM](https://user-images.githubusercontent.com/6547887/73491199-0d844780-437c-11ea-86d0-44123f0bb6da.png)

**Comment by mattdudys** [comment]
Which method or endpoint are you calling that returned this?

**Comment by dustinpaluch** [comment]
I'm calling 

`get_user( 'foo@bar' )`

Which eventually calls `httpRequestCurl( 'user', $data, 'GET' )`

Where `$data` is

```
[
  'api_key' => 'OURKEY',
  'format' => 'json',
  'json' => '{"id":"foo@bar","key":"email","fields":{"email":1,"lists":1,"vars":1}}',
  'sig' => 'SIG',
]
```

And the response I get from curl_exec [(Sailthru_Client.php#L1435)](https://github.com/sailthru/sailthru-php5-client/blob/master/sailthru/Sailthru_Client.php#L1435) is 

```
HTTP/1.1 200 OK
Date: Fri, 31 Jan 2020 15:29:42 GMT
Server: Sailthru
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Rate-Limit-Limit: 36000
X-Rate-Limit-Remaining: 35999
X-Rate-Limit-Reset: 1580484600
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json

{"error":99,"errormsg":"Invalid email: foo@bar"}
```

**Comment by mattdudys** [comment]
We maintain an internal email and email domain blacklist which was returning error code 11 as expected. This example is a malformed email address which fell into a more general error "invalid key value" validation logic which was returning error code 99.

I've pushed out a fix to return error code 11 if there is a malformed email address in /user. Can you give it a try and let us know how it goes?

**Comment by dustinpaluch** [comment]
Yup, getting 11 now. You might want to update the [Notes](https://getstarted.sailthru.com/developers/api/user/#Error_Codes) line for error code 11 to say "Email is invalid or banned".

Thanks!
